package com.apkpatcher.ui;

import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.util.Base64;

public class banner {

    public static void banner() {

        String date = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yy"));

        String logo = "ICAgICAgIPCfh67wn4ezIFdlbGNvbWUgQnkgVGVjaG5vIEluZGlhIPCfh67wn4ezCgogICAgICAgICAgICAgICAgIHV1dXV1dXUKICAgICAgICAgICAgIHV1JCQkJCQkJCQkJCR1dQogICAgICAgICAgdXUkJCQkJCQkJCQkJCQkJCQkJHV1CiAgICAgICAgdSQkJCBUZWNobm8gLSBJbmRpYSAkJCR1CiAgICAgICAgdSQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkdQogICAgICAgdSQkJCQkJCBBUEsgUEFUQ0hFUiAkJCQkJCR1CiAgICAgICB1JCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJHUKICAgICAgIHUkJCQkJCQiICAgIiQkJCIgICAiJCQkJCQkdQogICAgICAgIiQkJCQiICAgICAgdSR1ICAgICAgICQkJCQiCiAgICAgICAgJCQkdSAgICAgICB1JHUgICAgICAgdSQkJAogICAgICAgICQkJHUgICAgICB1JCQkdSAgICAgIHUkJCQKICAgICAgICAgIiQkJCR1dSQkJCAgICQkJHV1JCQkJCIKICAgICAgICAgICIkJCQkJCQkIiAgICIkJCQkJCQkIgogICAgICAgICAgICB1JCQkJCQkJHUkJCQkJCQkdQogICAgICAgICAgICAgdSQiJCIkIiQiJCIkIiR1CiAgdXV1ICAgICAgICAkJHUkICQgJCAkICR1JCQgICAgICAgdXV1CiB1JCQkJCAgICAgICAgJCQkJCR1JHUkdSQkJCAgICAgICB1JCQkJAogICQkJCQkdXUgICAgICAiJCQkJCQkJCQkIiAgICAgdXUkJCQkJCQKdSQkJCQkJCQkJCQkdXUgICAgIiIiIiIgICAgdXV1dSQkJCQkJCQkJCQKJCQkJCIiIiQkJCQkJCQkJCR1dXUgICB1dSQkJCQkJCQkJCIiIiQkJCIKICIiIiAgICAgICIiJCQkJCQkJCQkJCR1dSAiIiQiIiIKICAgICAgICAgICB1dXV1ICIiJCQkJCQkJCQkJHV1dQogIHUkJCR1dXUkJCQkJCQkJCR1dSAiIiQkJCQkJCQkJCQkdXV1JCQkCiAgJCQkJCQkJCQkJCIiIiIgICAgICAgICAgICIiJCQkJCQkJCQkJCQiCiAgICIkJCQkJCIgICAgICAgICAgICAgICAgICAgICAgIiIkJCQkIiIKICAgICAkJCQiICAgICAgICAgICAgICAgICAgICAgICAgICQkJCQiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIPCThIIg4Y6h6qud4oSRIPCThpAg77i744OH4pWQ5LiAIOC/lyDQr8y9zZNLzL3NkyDgv5cK4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlHzigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJR84oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlAogICAgICBOYW1lICAgICAgIHwgICAgIFRlbGVncmFtICAgICB8ICAgICAgT1dORVIgICAgICAgfCAgIERhdGUK4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlHzigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJR84oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlArjgIxUZWNobm8gSW5kaWHjgI0gfCBAcmt0ZWNobm9pbmRpYW5zIHwgQFJLX1RFQ0hOT19JTkRJQQ==";
        
        String b64 = "4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlOKAlHzigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJTigJR84oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCU4oCUfOKAlOKAlOKAlOKAlA==";

        System.out.println(b64ToString(logo) + " | " + date);
        System.out.println(b64ToString(b64));
    }
    
    public static String b64ToString(String b64) {
    try {
        return new String(
                Base64.getDecoder().decode(b64),
                StandardCharsets.UTF_8
        );
    } catch (IllegalArgumentException e) {
        e.printStackTrace();
        return null;
    }
}
    
    
}